### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by wolverdude** [anotherminh/Pixelate#1]
Awesome work Minh! Your wireframes and planning are top-notch! Some notes for improvement:

This plan is really detailed. That's good and bad. It tells me you've thought through the project well, but on the other hand, a lot of your planning is likely to go to waste as soon as you go to implement a feature and realize that what you'd thought at a high-level just isn't what's going to work at ground zero. Better to over-prepare though. I think you're gonna gain a lot from this experience!

Your "Minimum Viable Product" isn't very minimal. The question is not "What is the smallest feature set you'd _like_ to implement?" but "What is the minimum feature set _required_ for the project to be a functional website?" It's often much smaller than you'd think. All you really need is the ability to signup/signin, do the one or two essential site activities, and navigate. Having other things is a major plus, but that's the functional core. So long as you have that, you have _something_.

1.5 days may not be enough time to put the canvas widget together. Don't forget to budget time for unforeseen issues that might come up. We don't know how well React and canvas work together, for instance. Really, I think this project is a little ambitious as a whole. Always anticipate a day or two of time spent banging your head against a wall.

Also, be careful not to spend too much time on the canvas. Don't succumb to the temptation to make it [too fancy](http://sigilmaster.com/). On the one hand, you do want it to be impressive, since it's the core of your project, but on the other hand, it could turn into a massive time suck and kill the rest of your features. You want to show employers all that you can do, not just one thing you can do.

How are you going to serialize the canvas contents? This is a very important consideration.

Make sure that you also do authorization at the API level, not just in the component views.

**Comment by anotherminh** [comment]
Thanks for the feedback, Jon! I minimized the MVP as you suggested.  Didn't end up changing my timeline, though, because I'm ahead of schedule.  React and canvas works together well, thanks to refs.
